Revised vision layout
goinvo/goinvo.com pull request #345
Opened 2021-05-19 20:33 UTC by ericbenwa

This is a work in progress.
Need to revise images, styles, and tweak layout some.

2021-05-19 20:35 UTC, craigmcginley commented
Deploy Preview for *loving-austin-5f2eff* ready!

Built with commit 3d2a93569ee299b667fe1f80ff149a8cf1189e9c

https://deploy-preview-345--loving-austin-5f2eff.netlify.app

2021-05-20 21:26 UTC, ericbenwa commented
Ready for a review.

Side-note: I noticed a few items pop up in Terminal following yarn develop
"GitHub found 1 vulnerability on goinvo/goinvo.com's default branch (1 high)"

warn ESLintError: 
/Users/ericbenoit/Sites/goinvo.com/src/pages/index.js
  331:19  warning  Using target="_blank" without rel="noreferrer" is a security risk

warn ESLintError: 
/Users/ericbenoit/Sites/goinvo.com/src/components/header.js
  63:9  warning  Visible, non-interactive elements with click handlers must have at least one keyboard listener

I don't think it's a result of the changes I made but let me know if these should be fixed or we're already aware and not to worry.

2021-05-25 17:56 UTC, craigmcginley requested changes

2021-05-25 17:56 UTC, craigmcginley commented on src/pages/vision/index.js
> +              The future of healthcare is...
The margin for this line seems off on mobile view, close to header on top, extra space to next text line on bottom. Up to you on that one though.

2021-05-25 17:56 UTC, craigmcginley commented on src/pages/vision/index.js
> +          <div className="max-width content-padding pad-vertical--only-lg">
This is repeating container classes like `max-width`, `content-padding`, and `equal-height-rows` too much. If you don't need to break out of the max-width container (like to change the background color or something), then you can just wrap all these in one container. Also `equal-height-rows` isn't doing anything here. If you want all these rows to be the same height you have to group the `pure-g` all inside one `equal-height-rows` container (you can check the services page for an example of this).

2021-05-25 17:56 UTC, craigmcginley commented on src/pages/vision/index.js
> +        <div className="vision">
Can probably remove this wrapper element.

2021-05-25 17:56 UTC, craigmcginley commented on src/pages/vision/index.js
> -import axios from 'axios'
Since this is the only page that needed axios, we can remove this dependency now. `yarn remove axios` and commit that change (it should update package.json and yarn.lock).

2021-05-25 17:57 UTC, craigmcginley commented
> Ready for a review.
> @craigmcginley
> 
> Side-note: I noticed a few items pop up in Terminal following yarn develop
> "GitHub found 1 vulnerability on goinvo/goinvo.com's default branch (1 high)"
> 
> warn ESLintError:
> /Users/ericbenoit/Sites/goinvo.com/src/pages/index.js
> 331:19 warning Using target="_blank" without rel="noreferrer" is a security risk
> 
> warn ESLintError:
> /Users/ericbenoit/Sites/goinvo.com/src/components/header.js
> 63:9 warning Visible, non-interactive elements with click handlers must have at least one keyboard listener
> 
> I don't think it's a result of the changes I made but let me know if these should be fixed or we're already aware and not to worry.

These warnings are fine for now.

2021-05-25 20:00 UTC, ericbenwa commented
@craigmcginley Take a peek. Did I revise appropriately?

2021-05-25 21:08 UTC, craigmcginley approved these changes

2021-05-26 14:04 UTC, merged