Open source page
goinvo/goinvo.com pull request #371
Opened 2022-01-20 16:20 UTC by Ines-C-Amri

- Adding new page for open source healthcare

2022-01-20 16:23 UTC, craigmcginley commented
✔️ Deploy Preview for *loving-austin-5f2eff* ready!


🔨 Explore the source changes: abfa13e74000fe3d2b74328f6a1df235a3d53e3b

🔍 Inspect the deploy log: [https://app.netlify.com/sites/loving-austin-5f2eff/deploys/61e98bc96b13ca0007aa6435](https://app.netlify.com/sites/loving-austin-5f2eff/deploys/61e98bc96b13ca0007aa6435)

😎 Browse the preview: [https://deploy-preview-371--loving-austin-5f2eff.netlify.app](https://deploy-preview-371--loving-austin-5f2eff.netlify.app)

2022-01-28 12:59 UTC, jen-p reviewed
left some mostly editorial notes

2022-04-01 03:43 UTC, craigmcginley requested changes

2022-04-01 03:43 UTC, craigmcginley commented on src/components/os-categories-list.js
> +class CategoriesList extends Component {
We can actually delete this entire file since we reverted back to using the default CategoriesList component previously.

2022-04-01 03:43 UTC, craigmcginley commented on src/components/os-client-logos.js
> +class ClientLogos extends Component {
Since this is only ever used once (on your OSHC page), we technically don't need a component. we could basically take all the HTML in this component and render it directly in your page instead. If we do keep the component, I'd change the name of the class here to `OSClientLogos` or something different than the original.

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/index.js
> +                      are provided with better care with open source software we
Note: Copy check, follow up in discussion

2022-04-01 03:43 UTC, craigmcginley commented on src/data/categories.json
> +    "link": "/open-source-healthcare/?category=open-source-healthcare-vision"
Title says products and innovation... link to the first "vision" segment or the second "design + products" section?

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/index.js
>                        will flow through the software we've designed in 2019.
not related to your code, but maybe we should figure out a better phrasing for this since it says "in 2019".. sounds a bit off for being 2022 now.

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/index.js
> +              Leverage our thoroughly researched and tested materials and supplement it
"supplement it to" doesn't sound quite right. "and supplement your current product"?

2022-04-01 03:43 UTC, craigmcginley commented on src/styles/components/_carousel.scss
> +    bottom: -50px;
same thing for this file as with the javascript component file, changes will apply everywhere, so let's review options together

2022-04-01 03:43 UTC, craigmcginley commented on src/styles/_images.scss
> +    max-height: 50%;
Doesn't appear to be used anywhere, can probably delete this selector

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/work.js
> +        {/* <Collapsible
can delete all this commented out code if we no longer need it

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/services.js
> +  //   title: 'Open Source development and support',
we can delete if no longer using this. we're sure though?

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/open-source-healthcare.js
> +const ColoredLine = ({ color }) => (
this doesn't seem to be used anywhere, delete?

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/open-source-healthcare.js
> +import Quote from '../components/quote'
the quote component isn't used here, so we can delete this one line

2022-04-01 03:43 UTC, craigmcginley commented on src/pages/open-source-healthcare.js
> +import React, { Component } from 'react'
There's stuff we should go over together in this file. Many unused code we can delete, and some responsiveness issues with styling. Overall looking pretty good though.

2022-04-01 17:40 UTC, craigmcginley commented on gatsby-config.js
> +    // },
We can leave this commented out code because we may want to bring it back when we update the packages

2022-09-29 00:30 UTC, closed without merging