Draft of Inside Tracker case study.
goinvo/goinvo.com pull request #395
Opened 2022-05-02 18:51 UTC by ericbenwa

2022-05-02 18:54 UTC, craigmcginley commented
### <span aria-hidden="true">✅</span> Deploy Preview for *loving-austin-5f2eff* ready!


|  Name | Link |
|---------------------------------|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | cb358eba6c3b441d9dc9f2a7030382bb8bf3889d |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/loving-austin-5f2eff/deploys/6270281f984adb0009f35cc8 |
|<span aria-hidden="true">😎</span> Deploy Preview | https://deploy-preview-395--loving-austin-5f2eff.netlify.app |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://app.netlify.com/qr-code/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL2RlcGxveS1wcmV2aWV3LTM5NS0tbG92aW5nLWF1c3Rpbi01ZjJlZmYubmV0bGlmeS5hcHAifQ.-Ifwsto8yDiV7CksAYCr1Wgv3zbp3F7ftnMNUoueuzY)<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/loving-austin-5f2eff/settings/deploys#deploy-notifications)._

2022-05-02 20:54 UTC, jsonin approved these changes

2022-05-02 20:57 UTC, merged

2022-05-02 21:07 UTC, jen-p requested changes

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +The reason patients use software like Inside Tracker is to get the data they want, in the right way, with as little delay or distraction as possible. The patient's mission is to understand the bio an
The last sentence sounds really weird. What does it mean to be the data, and make the data be? Can we shave it down or break it up? Feels like we're trying too hard to be cool and overcomplicating our words. 

There's also a voice change where the patient becomes me.

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +Bioassay results combined with precision nutrition advice are data rich. Revealing more and more detail as the patient understands more and more about their health and nutrition is a proven design te
the 'and more's are not needed and slow down the sentence

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +Bioassay results combined with precision nutrition advice are data rich. Revealing more and more detail as the patient understands more and more about their health and nutrition is a proven design te
By ... to makes... is not grammatically correct, we're missing a subject in there somewhere.

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +The bioassay results have resonated with InsideTracker patients as an easy-to-understand return-of-information visualization. The designed technique has been live and in-use for a decade!
above we have return of information without dashes, I don't think we need them here.

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +10 years later and a 10x bigger company, Inside Tracker asked for another Design bump. This time, the business wanted to grow services around health goals and everyday habits.
Design shouldn't be capitalized?

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +A nutrition agent, working on your behalf, to organize your food life and better your health, was a new avenue for Inside Tracker. By incorporating feedback from patients, stakeholders, scientists, a
no comma needed after behalf.

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +A nutrition agent, working on your behalf, to organize your food life and better your health, was a new avenue for Inside Tracker. By incorporating feedback from patients, stakeholders, scientists, a
ie.,

2022-05-02 21:07 UTC, jen-p commented on src/case-studies/inside-tracker-nutrition-science.md
> +A nutrition agent, working on your behalf, to organize your food life and better your health, was a new avenue for Inside Tracker. By incorporating feedback from patients, stakeholders, scientists, a
the next iteration?

2022-05-02 21:45 UTC, jsonin commented on src/case-studies/inside-tracker-nutrition-science.md
> +<Quote quotee="From Bathroom to Healthroom" quoteeSub="">Data let us live aware of our health. For example, when we are messaged that ice cream is high in fat, high in sugar, and high in cow's milk,
It's a quote. Let's not change that particular entry.

2022-06-15 18:44 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +Nutrition science rightly advocates for Michael Pollen's trio. And yet, personalized food choices, generated for you, based on chemistry, DNA, activity, biome, and goals are only just arriving based
got it

2022-06-15 18:44 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +The bioassay results have resonated with InsideTracker patients as an easy-to-understand return-of-information visualization. The designed technique has been live and in-use for a decade!
got it

2022-06-15 18:44 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +A nutrition agent, working on your behalf, to organize your food life and better your health, was a new avenue for Inside Tracker. By incorporating feedback from patients, stakeholders, scientists, a
got it

2022-06-15 18:44 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +10 years later and a 10x bigger company, Inside Tracker asked for another Design bump. This time, the business wanted to grow services around health goals and everyday habits.
got it

2022-06-15 18:45 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +metaDescription: 'Personalized Food based on your DNA, blood, and habits.'
got it

2022-06-15 18:46 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +How does the InsideTracker food engine help patients pick the right food, at the right time, for my best health?
got it

2022-06-15 19:00 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +Inside Tracker is a quantified food and nutrition service, creating a hard science-based food engine, which along side your blood work and lifestyle, can synthesize a hyper-personalized food plan.
got it

2022-06-15 19:00 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +#### Show the Results, beautifully
got it

2022-06-15 19:01 UTC, ericbenwa commented on src/case-studies/inside-tracker-nutrition-science.md
> +Nutrition science is complicated. How foods interact with your chemistry and what food our particular bodies and minds need needs to be shown in straight-forward methods. It shouldn’t take a Masters
got it