Open source health design
goinvo/goinvo.com pull request #399
Opened 2022-06-08 17:53 UTC by Ines-C-Amri

I created a new Open Source page with the new designs --this is just the start

2022-06-16 16:11 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +              organizations to design more than 60 open source projects to the
"we've partnered..."

"Nonprofit"... hyphenate? the wiki article doesn't.
https://en.wikipedia.org/wiki/Nonprofit_organization

2022-06-16 16:12 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +              solve most pressing healthcare issues.
"to solve..."
currently reads as "to the solve..."

2022-06-16 16:14 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                  Studio internal investment <br /> in open source projects
Studio internal investment ==> GoInvo investment ... ?

2022-06-16 16:14 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                <span style={numbersStyle}>65+</span>
60 or 65?
Stat above is over 60 and here is 65+

2022-06-16 16:15 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +              Health and Human Services. We design and build orolects with
"orolects" ? projects?

2022-06-16 16:16 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +              available to benefit communities and society as a whole
insert period

2022-06-16 16:18 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                    that they can live their healthiest life
insert period

2022-06-16 16:18 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                    Rosie is an open source Health Manager to support user
user => people

2022-06-16 16:19 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                    share that data in their community to meet their health
community => care team ?

2022-06-16 16:19 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                  {/* <a>Learn more about the project</a> */}
Should this link to hGraph?

2022-06-16 16:20 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                    and the general public
insert period

2022-06-16 16:21 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                We’re a growing communtiy of healthcare professionals, designers
typo "community"

2022-06-16 16:22 UTC, ericbenwa commented on src/pages/open-source-health-design.js
> +                ideas.
"Subscribe to our Open Source Health Design newsletter where we regularly share updates on projects and organize online events giving you the opportunity to connect with a diverse network, ask questions, show your work, and exchange ideas."

tweaks on plural for events and added comma

2022-06-24 15:09 UTC, ericbenwa commented
Link to LHL is going to the homepage. I know LHL feature isn't live but can we guesstimate its URL and drop in now?

Rosie is an open source health manager to support people aggregate all their health data...
("to support people aggregate" sounds a little off)
=? a suggestion ("to support people aggregating")

"Here is the debut issue of our Open Source Health Journal, advocating open source ideas to change healthcare for the better."
(Since we only have one, with a second not coming in short-term, do we rewrite to remove the word "Debut"?)

2022-06-27 17:04 UTC, craigmcginley requested changes

2022-06-27 17:04 UTC, craigmcginley commented on src/pages/open-source-health-design.js
> +                <Card link="https://www.goinvo.com/work/hgraph">
I think for "internal" links, aka ones going to somewhere within www.goinvo.com we should just use the path `link="/work/hgraph"`

For links going elsewhere:
`link="https://www.google.com/" externalLink={true}`

Doing this helps with page load performance, and can also be used for special navigation techniques (which I don't think we employ on our site)

2022-06-27 17:04 UTC, craigmcginley commented on src/pages/open-source-health-design.js
> +                <Card link="/">
you can add `/vision/living-health-lab` here and it will be merged soon

2022-06-28 17:59 UTC, craigmcginley approved these changes

2022-06-28 18:03 UTC, craigmcginley approved these changes

2022-06-28 18:24 UTC, merged